### ISSUE TITLE
Slack scopes?

### ISSUE THREAD

**Issue by funcho** [yuca-live/tapioca#15]
Which are the scopes needed?

**Comment by funcho** [comment]
Code: (tapiocaLambda.js:98)
`const conversationData = await slack.conversations.open({ users: userIds });`

Log from AWS Lambda:
`2022-02-07T18:23:56.876Z	179ebd8c-5a5b-4e55-865a-77296ebd3745	INFO	createConversationAndPostMessage creating conversation with users=UDHNX21FS,UDJHS2KHB
2022-02-07T18:23:57.008Z	179ebd8c-5a5b-4e55-865a-77296ebd3745	ERROR	handler could not handle correctly teamId=1 Error: missing_scope
    at exec (/var/task/node_modules/slack/src/_exec.js:11:15)
    at Object._execWithToken (/var/task/node_modules/slack/src/_factory.js:31:16)
    at createConversationAndPostMessage (/var/task/tapiocaLambda.js:98:54)
    at /var/task/tapiocaLambda.js:140:50
    at Array.map (<anonymous>)
    at /var/task/tapiocaLambda.js:140:35
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 0)
2022-02-07T18:23:57.008Z	179ebd8c-5a5b-4e55-865a-77296ebd3745	INFO	handler tapioca conversation maker finished`
